language: node_js

node_js:
  - '4'
  - '6'
  - '7'

matrix:
  include:
    - node_js: '4'
      script: npm run code && npm test
    - node_js: '6'
      script: npm run code && npm test && npm run test-sauce
    - node_js: '7'
      script: npm run code && npm test
