language: node_js

node_js:
  - '4'
  - '6'
  - '7'
  - '8'

matrix:
  include:
    - node_js: '4'
      env: SCRIPT=ci-node
    - node_js: '6'
      env: SCRIPT=ci-node-sauce
    - node_js: '7'
      env: SCRIPT=ci-node
    - node_js: '8'
      env: SCRIPT=ci-node
  exclude:
    # Note: Workaround travis-ci/travis-ci#4681
    # Exclude default job which lacks our included environment variables.
    - node_js: '4'
    - node_js: '6'
    - node_js: '7'
    - node_js: '8'

script: npm run $SCRIPT
