language: node_js

node_js:
  - '4'
  - '6'
  - '7'

env:

matrix:
  include:
    - node_js: '4'
      env: SCRIPT=ci-node
    - node_js: '6'
      env: SCRIPT=ci-node-sauce
    - node_js: '7'
      env: SCRIPT=ci-node

script: npm run $SCRIPT
